# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:           /:categories/:title/

# Analytics and webmaster tools stuff goes here
google_analytics:    UA-70975044-1 #UA-73537086-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Setup
timezone:            europe/berlin
locale:              de_DE
name:                Personal Website of Kristin Baumann
title:               Kristin Baumann
tagline:             Frontend Developer - DataVis Lover - Travel Addict
description:         Personal website of Kristin Baumann
url:
url_public:          http://www.kristin-baumann.com
baseurl:             /
baseurl_js:          /assets/js/
avatar:              /assets/img/Baumann_touched_square.jpg
icon:                /assets/img/icons/logo-150.png
disqus:              kristin-baumann
gems:
  - jemoji

future:              true
highlighter:         rouge
markdown:            kramdown
kramdown:
  input:             GFM  # GitHub Flavored Markdown

author:
  name:              Kristin Baumann
  url:               kristin-baumann.com
  github:            kristinbaumann
  medium:            kristin_baumann
  twitter:           kristin_baumann
  linkedin:          kristinbaumann
  xing:              Kristin_Baumann9
  email:             mail@kristin-baumann.com

# Server
exclude:             [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "haml", "Gemfile", "Gemfile.lock", "gulpfile.js"]
port:                4001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
