# Analytics and webmaster tools stuff goes here
google_analytics:    UA-70975044-1 

# Setup
timezone:            europe/berlin
locale:              de_DE
name:                Personal Website of Kristin Baumann
title:               Personal Website of Kristin Baumann
tagline:             Frontend Developer - DataVis Lover - Travel Addict
description:         Frontend Developer - DataVis Lover - Travel Addict
url:
url_public:          http://www.kristin-baumann.com
baseurl:             /
baseurl_js:          /assets/js/
avatar:              /assets/img/Baumann_touched_square.jpg
icon:                /assets/img/icons/logo-150.png

author:
  name:              Kristin Baumann
  url:               kristin-baumann.com
  github:            kristinbaumann
  medium:            kristin_baumann
  twitter:           kristin_baumann
  linkedin:          kristinbaumann
  xing:              Kristin_Baumann9
  email:             mail@kristin-baumann.com

# Server
exclude:             [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "haml", "Gemfile", "Gemfile.lock", "gulpfile.js"]
port:                4001